### ISSUE TITLE
Automate TWIST protocol for LIMS

### ISSUE THREAD

**Issue by annaengstrom** [Clinical-Genomics/clinical_EPPs#143] opened 2020-04-06 19:53 UTC
**Summary of issue**
*As many adjustments and changes have been made in the TWIST workflow while this issue was developed it was decided (CS and MB) to verify all changes in the same verification test. The verification is documented in issue #128 .*

The existing workflow for the TGA-sample preparation and target enrichment (TWIST v2) has been adjusted to the fit the automated procedure (see doc ***2125***). The affected protocol is **Library prep TWIST** and the new workflow will be named **TWIST v3**.

The protocol now consists of 3 steps:
- *Aliquot samples for enzymatic fragmentation TWIST*
- *Enzymatic fragmentation TWIST*
- *KAPA Library preparation*

***Aliquot samples for enzymatic fragmentation***
This is the same as it was in the previous version except that the script *Calculate volumes* sets *Amount needed*. This was done manually before. The script set up is described below. *Amount* is the amount DNA available and is based on values set in the Initial QC procotol (concentration and volume).

If Amount >=250ng set Amount needed 250ng
If Amount >=50ng <250ng set Amount needed 50ng
If Amount >=10ng <50ng set Amount needed 10ng
If Amount <10ng set Amount needed = Amount

In the end of this step it's possible to either choose to continue with step *Enzymatic fragmentation TWIST* or *KAPA Library preparation* depending on if the samples need to be fragmented or not.

***Enzymatic fragmentation TWIST***
This is the same as it was in the previous version except that there is a new script for creating a file that is needed in when running the prep automatically on Hamilton.

This step must create a file containing information in following [format](https://drive.google.com/file/d/1Yi1zgxg8_cACBEx0GEHMelH0FnvzkbaS/view). The file in this step is only used for number of samples on Hamilton. As the indicies are not chosen in this step a **-** is set in column *Index well*.

***KAPA Library preparation***
Previous steps:
End-Repair and A-tailing TWIST
Adapter Ligation TWIST
Bead Purification (Adapter Ligation) TWIST
Add Index Primers and Amplify Library TWIST
Bead Purification (pre hybridization) TWIST

is collided into one step *KAPA Library preparation*. Indicies are chosen in this step, where 2 different sets are available. A file like the one created in step *Enzymatic fragmentation TWIST* is created by a script. Now the column *Index well* will have values. The index well position is taken from the **index name**, where the well position is stated. Lot no, thermal cyclers and method document is also registered in this step.

**After the samples have been through this protocol they are passed on to protocol *Library validation QC TWIST*.**

**Comment by KarinSollander** [comment] 2020-05-05 13:40
Discussion with AG concerning the layout of KAPA workflow:

* Samples arrive from Initial QC Twist

* Step 1 Aliquotation - 3 different amounts (10, 50 and 250 ng), user should also be able to choose manually if the amount is below 10 ng. The concentration will affect information downstream. (This should be done both for samples for Enzymatic fragmentation and those which go directly to End Repair and A-tail step, but should be made in separate steps). Today aliquotation will be made manually but in the future, this step should be made at Hamilton.

* Enzymatic fragmentation step - Decided from the Aggregation QC step if the samples go through this step. This step must create a file containing information in following [format](https://drive.google.com/open?id=1Yi1zgxg8_cACBEx0GEHMelH0FnvzkbaS). Information not relevant to the step can be "fake" (Ligation Master Mix, Index Well and PCR Plate). (File is only used for number of samples). Lot#, document number (no available document number yet, Method - Automated KAPA Library prep) and version and PCR machine registration.

* End Repair to Amplification - Sample placement, bring 1-2 plates together that was created in the aliquotation step. Index placement, use the new indices: IDT Xgen Dupseq. Creation of a file to Hamilton. Based on information from the Aliquotation step, sample amount, the file should contain  certain values.

| Amount | Amplification Master Mix | PCR Plate |
| :----: | :----: | :----: |
| =< 10 ng | B | Plate 3 |
| 50 ng | A | Plate 2 |
| 250 ng | A | Plate 3 |

Lot#, document number (no available document number yet, Method - Automated KAPA Library prep) and version and PCR machine registration. PCR machines should be registered for the following steps: End Repair and A-tail*, Adapter ligation*, PCR Plate 1*, PCR Plate 2, PCR Plate 3. Steps marked with (*) should be required. First two steps should contain PCR machines in Pre lab and the three for PCR plates should have the Post machines.

* Post amplification Bead purification - Should look like the one used today. Exception: must create or copy file form previous step.

* Continue with "Library validation QC Twist v1"

**Comment by mayabrandi** [comment] 2020-05-11 06:17
Jag pratade med Anna G gällande namnet på det "nya" kombinerade steget i LIMS som vi diskuterade förra veckan. Mitt förslag var "End-Repair to Library Amplification KAPA" men Anna föreslog "Endrepair/Atailing, Ligation, Amplification KAPA" istället. Skulle det fungera att byta?

**Comment by annaengstrom** [comment] 2020-05-11 15:21
I think that the new name is good.

**Comment by annaengstrom** [comment] 2020-05-15 13:50
This should be completed before test run on Hamilton.

@mayabrandi what is your estimated time plan for completing this?

**Comment by mayabrandi** [comment] 2020-05-15 13:54
I will finish this on monday. Did not have time for it today unfortunately.

**Comment by cesve** [comment] 2020-05-15 14:50
@mayabrandi if you need help testing the protocol I can help you!

**Comment by mayabrandi** [comment] 2020-05-18 07:51
This needs to be in place before Wednesday morning. Correct?

**Comment by mayabrandi** [comment] 2020-05-18 07:51
Thanks @cesve ! Ill let you know when its time!

**Comment by cesve** [comment] 2020-05-18 08:09
@mayabrandi it doesn't have to be done before Wednesday!

**Comment by cesve** [comment] 2020-05-20 08:53
@annagellerbring would it be possible to use the same steps both for manual and automated prep? End-repair --> Amplification

**Comment by annagellerbring** [comment] 2020-05-20 12:31
@cesve I guess it would be possible since all adjustments we do in manual we also do for a Hamilton prep: which means adjusting adapter volume, running different pcr cycles.

**Comment by cesve** [comment] 2020-05-25 07:18
@annaengstrom @annagellerbring: Me and @KarinSollander discussed whether the last bead cleaning should be included in the ERAT-step?

+ When we do the bead-cleaning we have to place the samples back in the exact same position as they were before if several plates have been used in the amplification. Perhaps it can be complicated if we have other samples in this step? What if you, by mistake, take the wrong samples when you start this lims step?
+ There is no safe stopping point between the amplification and the bead-cleaning and after the amplification you have to continue directly with the bead-cleaning.

**Comment by cesve** [comment] 2020-05-25 07:22
@annaengstrom @annagellerbring @KarinSollander would it be possible to divide the ERAT-step (by ERAT-step I mean the lims step that today = End-Repair and A-tailing TWIST, Adapter Ligation TWIST, Bead Purification (Adapter Ligation) TWIST, Add Index Primers and Amplify Library TWIST) into:

1. End-repair & A-tail, Adaptor lig. + bead cleaning.
2. PCR-amplification + bead-cleaning.

**Comment by annaengstrom** [comment] 2020-05-25 09:49
Is the idea to have one workflow for the manual prep and one for the automated?

**Comment by KarinSollander** [comment] 2020-05-25 10:38
> Is the idea to have one workflow for the manual prep and one for the automated?

The first idea was to have two separate protocols for the prep-part of the workflow. But it would be a lot easier if we could use the same protocol for both. The major difference with the new protocol is that several steps are combined into one (or two) and that it creates a file for Hamilton.

**Comment by KarinSollander** [comment] 2020-05-25 10:40
> @annaengstrom @annagellerbring @KarinSollander would it be possible to divide the ERAT-step (by ERAT-step I mean the lims step that today = End-Repair and A-tailing TWIST, Adapter Ligation TWIST, Bead Purification (Adapter Ligation) TWIST, Add Index Primers and Amplify Library TWIST) into:
> 
> 1. End-repair & A-tail, Adaptor lig. + bead cleaning.
> 2. PCR-amplification + bead-cleaning.

I don't like this division, then we would have three different files during one prep since the indices are selected in the amplification step.

**Comment by annaengstrom** [comment] 2020-05-25 10:45
I think it could be a problem to have the same workflow for the manual and automated if we run manually often, but probably we won't right?

**Comment by cesve** [comment] 2020-05-25 10:47
> > Is the idea to have one workflow for the manual prep and one for the automated?
> 
> The first idea was to have two separate protocols for the prep-part of the workflow. But it would be a lot easier if we could use the same protocol for both. The major difference with the new protocol is that several steps are combined into one (or two) and that it creates a file for Hamilton.

Let's decide to have it as one protocol then. Then it will be easier if a sample needs to transfer from auto to manual or the other way around.

**Comment by cesve** [comment] 2020-05-25 10:49
> I think it could be a problem to have the same workflow for the manual and automated if we run manually often, but probably we won't right?

We should run as much as possible on Hamilton and manually only if Hamilton is broken. Like we do with WGS. But what type of problem do you think we will have if we combine the protocols and you run the prep manually?

**Comment by cesve** [comment] 2020-05-25 10:50
> > @annaengstrom @annagellerbring @KarinSollander would it be possible to divide the ERAT-step (by ERAT-step I mean the lims step that today = End-Repair and A-tailing TWIST, Adapter Ligation TWIST, Bead Purification (Adapter Ligation) TWIST, Add Index Primers and Amplify Library TWIST) into:
> > 
> > 1. End-repair & A-tail, Adaptor lig. + bead cleaning.
> > 2. PCR-amplification + bead-cleaning.
> 
> I don't like this division, then we would have three different files during one prep since the indices are selected in the amplification step.

Ok! Then it's better to skip this division.

**Comment by KarinSollander** [comment] 2020-05-25 11:25
> @annaengstrom @annagellerbring: Me and @KarinSollander discussed whether the last bead cleaning should be included in the ERAT-step?
> 
> * When we do the bead-cleaning we have to place the samples back in the exact same position as they were before if several plates have been used in the amplification. Perhaps it can be complicated if we have other samples in this step? What if you, by mistake, take the wrong samples when you start this lims step?
> * There is no safe stopping point between the amplification and the bead-cleaning and after the amplification you have to continue directly with the bead-cleaning.

The thought we had when we suggested to have the Post Amp Bead Cleaning as a separate step was that it enabled to finish The ERAT-to-Amplification step in the pre lab and then start the Post Amp Bead Cleaning step when entering the post lab. One benefit with that is that you don't have to register two different lot # for beads, water and EtOH etc. On the other hand, you have to register which PCR-machine to use for the amplification and perhaps you do that when you enter the post lab.

If the steps are separate (as suggested) there shouldn't be a sample placement step. All information should be transferred from the previous steps. Therefor, I don't see a contamination/mixup risk in dividing these steps in LIMS. This is one step that should be thoroughly tested if implemented (both in LIMS and on Hamilton). 

I think we should decide to combine all steps into one (including the Post Amp Bead Cleaning with the others) if we gain something or if it doesn't matter. We should **not** combine them if it complicates the work in LIMS (with lot# registration etc). Since I haven't worked with this manually I think it's better if you decide @annaengstrom @annagellerbring

**Comment by annaengstrom** [comment] 2020-05-25 12:20
> > @annaengstrom @annagellerbring: Me and @KarinSollander discussed whether the last bead cleaning should be included in the ERAT-step?
> > 
> > * When we do the bead-cleaning we have to place the samples back in the exact same position as they were before if several plates have been used in the amplification. Perhaps it can be complicated if we have other samples in this step? What if you, by mistake, take the wrong samples when you start this lims step?
> > * There is no safe stopping point between the amplification and the bead-cleaning and after the amplification you have to continue directly with the bead-cleaning.
> 
> The thought we had when we suggested to have the Post Amp Bead Cleaning as a separate step was that it enabled to finish The ERAT-to-Amplification step in the pre lab and then start the Post Amp Bead Cleaning step when entering the post lab. One benefit with that is that you don't have to register two different lot # for beads, water and EtOH etc. On the other hand, you have to register which PCR-machine to use for the amplification and perhaps you do that when you enter the post lab.
> 
> If the steps are separate (as suggested) there shouldn't be a sample placement step. All information should be transferred from the previous steps. Therefor, I don't see a contamination/mixup risk in dividing these steps in LIMS. This is one step that should be thoroughly tested if implemented (both in LIMS and on Hamilton).
> 
> I think we should decide to combine all steps into one (including the Post Amp Bead Cleaning with the others) if we gain something or if it doesn't matter. We should **not** combine them if it complicates the work in LIMS (with lot# registration etc). Since I haven't worked with this manually I think it's better if you decide @annaengstrom @annagellerbring

It sounds to me better if these are combined. We could have separate lot numbers for POST and PRE beads, water and ethanol for example.

**Comment by cesve** [comment] 2020-05-25 13:53
> > > @annaengstrom @annagellerbring: Me and @KarinSollander discussed whether the last bead cleaning should be included in the ERAT-step?
> > > 
> > > * When we do the bead-cleaning we have to place the samples back in the exact same position as they were before if several plates have been used in the amplification. Perhaps it can be complicated if we have other samples in this step? What if you, by mistake, take the wrong samples when you start this lims step?
> > > * There is no safe stopping point between the amplification and the bead-cleaning and after the amplification you have to continue directly with the bead-cleaning.
> > 
> > 
> > The thought we had when we suggested to have the Post Amp Bead Cleaning as a separate step was that it enabled to finish The ERAT-to-Amplification step in the pre lab and then start the Post Amp Bead Cleaning step when entering the post lab. One benefit with that is that you don't have to register two different lot # for beads, water and EtOH etc. On the other hand, you have to register which PCR-machine to use for the amplification and perhaps you do that when you enter the post lab.
> > If the steps are separate (as suggested) there shouldn't be a sample placement step. All information should be transferred from the previous steps. Therefor, I don't see a contamination/mixup risk in dividing these steps in LIMS. This is one step that should be thoroughly tested if implemented (both in LIMS and on Hamilton).
> > I think we should decide to combine all steps into one (including the Post Amp Bead Cleaning with the others) if we gain something or if it doesn't matter. We should **not** combine them if it complicates the work in LIMS (with lot# registration etc). Since I haven't worked with this manually I think it's better if you decide @annaengstrom @annagellerbring
> 
> It sounds to me better if these are combined. We could have separate lot numbers for POST and PRE beads, water and ethanol for example.

I agree! I don't think it's such a big deal that you write lot# for 2 different bead purifications in the same step. Especially since we have a lot of other lot# here. And as you said Karin, you probably have to start the PCR before you can write which thermal cycler you used.

**Comment by annagellerbring** [comment] 2020-05-25 14:23
I vote to make it as uncomplicated as possible: 1 workflow for both automated and manual, and one step from ERAT to post-amp clean up.

**Comment by KarinSollander** [comment] 2020-05-26 06:43
> I vote to make it as uncomplicated as possible: 1 workflow for both automated and manual, and one step from ERAT to post-amp clean up.

Then it's decided!
@mayabrandi I haven't changed anything in the description that we wrote. Talk to me or Cissi when you start to work with this, then we can change it together.

**Comment by KarinSollander** [comment] 2020-05-27 06:07
After a discussion with @mayabrandi we decided to change the file format to comma (,) separated *.txt (instead of *.csv). During the week there has been problems with file reading of *.csv in the Hamilton method when running it on different computers. The *.csv file change format depending on the setting on different computers, this has not been a problem with the *.txt file.

**Comment by mayabrandi** [comment] 2020-05-27 12:24
I have now set up a workflow TWIST v3 that is ready for testing. Who wants to validate the new WF?

**Comment by cesve** [comment] 2020-05-28 06:35
I can validate and test it Maya. I just need some input from the others to see if we need to make some adjustments.

I was also wondering about the fragmentation step. @KarinSollander did you try the file with empty values for everything except the sample placement? @mayabrandi was it possible to create this file?

**Comment by mayabrandi** [comment] 2020-05-28 07:01
Let me know when you want to start looking at it cissi. We can write the report together.

**Comment by KarinSollander** [comment] 2020-05-29 07:31
@mayabrandi i tested the file you sent:

[92-958734_KAPA_Hamilton (1).txt](https://github.com/Clinical-Genomics/clinical_EPPs/files/4700243/92-958734_KAPA_Hamilton.1.txt)

It didn't work. I did some troubleshooting and the file contains empty rows. When I removed them, I could use the file without problems.

[Test_remove-empty-lines_92-958734_KAPA_Hamilton (1).txt](https://github.com/Clinical-Genomics/clinical_EPPs/files/4700262/Test_remove-empty-lines_92-958734_KAPA_Hamilton.1.txt)

**Comment by cesve** [comment] 2020-05-29 07:43
Made some changes in the description. The following have been removed after discussions with everyone involved.

(- [x] The Twist workflow will remain as it is), except that there will be an option to chose the new protocoll which we will call "Automated Library Prep KAPA" (use moove samples for this. Add to **Aggregate QC (DNA) TWIST** ) Default ska vara automated.

**Comment by cesve** [comment] 2020-05-29 07:50
Aliquot samples for enzymatic fragmentation TWIST
Enzymatic fragmentation TWIST

@annaengstrom can we change the name to Aliquot samples for enzymatic fragmentation KAPA and Enzymatic fragmentation KAPA?

**Comment by cesve** [comment] 2020-05-29 07:57
> I have now set up a workflow TWIST v3 that is ready for testing. Who wants to validate the new WF?

Me and Karin will test it when it's ready.

**Comment by KarinSollander** [comment] 2020-05-29 09:53
Need help to control the index information in LIMS.

* Are we using the correct Label group?
* Is the well position in the label name the correct in the actual plate?

Who can help with this?
@annagellerbring @annaengstrom @AnnaZetterlund 
If you need more information on where to look in LIMS, talk to MB

**Comment by annaengstrom** [comment] 2020-05-29 10:30
@cesve The name with KAPA is better than Twist

@mayabrandi where should I look to see the last questions from @KarinSollander ?

**Comment by cesve** [comment] 2020-05-29 10:58
> Aliquot samples for enzymatic fragmentation TWIST
> Enzymatic fragmentation TWIST
> 
> @annaengstrom can we change the name to Aliquot samples for enzymatic fragmentation KAPA and Enzymatic fragmentation KAPA?

@mayabrandi is it possible to change the name of these steps and perhaps also protocols without messing things up? We can talk about this on Monday, it's not urgent.

**Comment by KarinSollander** [comment] 2020-06-02 10:41
KBS, AG and CS had a final meeting regarding the new protocol in LIMS. We went through all steps and discussed the outcome. [Notes](https://docs.google.com/document/d/1WAJ3N26hkG8n-WzqjP2jrua-QAVONNvmyk9hewcSLRM/edit?ts=5ed61b10) were taken both while planning the meeting and during the meeting.
Some actions was decided to take place:
- [ ] Check with AZ which sets of indices we are and will be using. **KBS**
- [ ] Indices to use: IDT DupSeq 10bp Set A and IDT DupSeq 10bp Set C. Well position needs to be transferred from the index name to Index Well column in file. **MB**
- [ ] Add new Method document in Prep step. **CS** have to publish a first version of the method and **MB** add in LIMS
- [ ] Check with **MB** if it’s possible to run the Make Placement Map script without filling the required fields. **CS**
- [ ] In placement map, remove three first rows (Project name, sample name and Sample ID) **MB**
- [ ] Add Source container and source well in table in Record detail steget. **MB**
- [ ] Add a comment filed for the Prep step. **MB**
- [ ] Create a script that chooses the Amount needed for the prep? (Based on Amount after QC?). **MB**
* If Amount >=250ng set Amount needed 250ng
* If Amount >=50ng <250ng set Amount needed 50ng
* If Amount >=10ng <50ng set Amount needed 10ng
* If Amount <10ng set Amount needed = Amount

@mayabrandi @cesve

**Comment by KarinSollander** [comment] 2020-06-04 05:35
AZ confirmed that we should use IDT DupSeq 10bp Set A and IDT DupSeq 10bp Set C

**Comment by KarinSollander** [comment] 2020-06-08 08:28
@mayabrandi 
I have found two issues with the file derived from LIMS:
* The PCR Plate must be named Plate1, Plate2 and Plate3 without a space between "Plate" and the number.
* Index well can't contain a 0 (zero) between the letter and the well number. E.g A01 can't be used, have to be written as A1 instead.

I'll attach a file created in LIMS but where I have made the changes necessary to be able to run on Hamilton.
[Change PCR Plate Index_8samples_Prep_92-960395_KAPA_Hamilton.txt](https://github.com/Clinical-Genomics/clinical_EPPs/files/4744741/Change.PCR.Plate.Index_8samples_Prep_92-960395_KAPA_Hamilton.txt)

**Comment by cesve** [comment] 2020-06-09 07:24
**Verification**
**Planned by: CS and MB**

Protocol/step | Test Specification | Pass/Fail | Comments
-- | -- | -- | --
Pre Processing |   |   |  
Step 1.  | Add 10 samples to the step. Check three samples to skip buffer exchange. Continue to next step and finish step. |   | Make sure the three samples were passed on to *, and that the rest of thesamples were placed in queue to Buffer Exchange
Step 2. Buffer Exchange | Place the samples in 96 well plate. Give some samples volume < 50 ul, and some smaples volume > 50 ul. Run the script to calculate voulems and the script to generate placement map. Continue to next step * |   | Make sure the volumes are correctly calculated both for the samples with voulme >50ul and samples with volume <50 ul. Check that the placement map is correct
Initial QC |   |   |  
Step 1. Depends on Workflow * |   |   | Check that all the 10 samples are in queue to this step after finishing Buffer Exchange. And that the container and well positions are as expected. Samples the did not go through Buffer exchange should have their original well positions and samples that went through buffer exchange should have the well positions they got in the placement of that step.

**Closed** 2020-06-18 09:14 UTC
